/* Given a string, define a function to return all its subsequences in an arraylist. A string is a subsequence of a given string 
   if it is generated by deleting some character of a given string without changing its order. */
import java.util.*;
public class Question_32 {
    static ArrayList<String> getStringSubsequences(String s)
    {
        ArrayList<String> ans = new ArrayList<>();
        if(s.length()==0)
        {
            ans.add("");
            return ans;
        }
        char curr=s.charAt(0);
        ArrayList<String> smallAns = getStringSubsequences(s.substring(1));
        for(String ss : smallAns)
        {
            if(!ans.contains(ss))
            ans.add(ss);
            if(!ans.contains(curr+ss))
            ans.add(curr+ss);
        }
        return ans;
    }
    public static void main(String args[])
    {
        try(Scanner sc=new Scanner(System.in))
        {
            System.out.print("Enter a string : ");
            String s=sc.nextLine();
            System.out.print("All the subsequences of the given string ar : "+getStringSubsequences(s));
        }

    }
}
